config/routes.rb
Rails.application.routes.draw do

resources :boards
resources :pins do
  #resources :comments
  member do
    post '/repost' => 'pins#repost'
  end

  member do
    post '/like' => 'pins#like'
  end
end

  devise_for :users
  root 'home#index'
  get ':username' => 'users#show', as: 'user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

  belongs_to :user
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :pin

  validates_uniqueness_of :pin_id, scope: :user_id
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates_presence_of :description

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_attached_file :pin_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pin_image, content_type: /\Aimage\/.*\z/


  def repost(user)
    repost_pin = self.dup
    repost_pin.user_id = user.id
    repost_pin.original_pin_id = self.id
    repost_pin.pin_image = self.pin_image
    repost_pin.save

  end

  def is_repost?
    self.original_pin_id.present?
  end

  def original_pin
    Pin.find(original_pin_id) if is_repost?
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boards
  has_many :pins
  has_many :likes
  has_many :liked_pins, through: :likes, source: :pin

  #@user = User.first
  #@user.likes
  #@user.liekd_pins.each do

  validates_uniqueness_of :username

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :avatar])

  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @boards = Board.all
  end

  def new
    @board = Board.new(user_id: current_user.id)
    @board = current_user.boards.build

  end

  def show
  end


  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, notice: "new board was created"
    else
      render :new

    end


  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: "board was updated"
    else
      render :edit
    end

  end

  def edit
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: "board was deleted"
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end

  def correct_user
      @board = current_user.boards.find_by(id: params[:id])
      redirect_to boards_path, notice: "Not authorized to edit this board" if @board.nil?
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :repost, :like]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  def repost
    @pin.repost(current_user)
    redirect_to pins_path
  end

  def like
    #@pin = Pin.find(params[:id]) -> set_pin으로
    @like = @pin.likes.build(user_id: current_user.id)
    if @like.save
      flash[:notice] = "you likeed this pin"
      redirect_to pins_path
    else
      flash[:notice] = "you didnt liked this pin"
      redirect_to pins_path
    end


  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pins_path, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :pin_image)
    end

    def correct_user
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to pins_path, notice: "Not authorized to edit this pins" if @pin.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by username: params[:username]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<h2>All boards </h2>

<% @boards.each do |board| %>
  <div>
    <h2><%= board.name %></h2>
    <p><%= link_to 'edit', edit_board_path(board) %> <%= link_to 'delete', board, method: :delete %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Hello종린!</h1>
  <p>3억</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '종린월드', root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to '종린월드', root_path, class: "active" %></li>
          <li><%= link_to 'Pins', pins_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'New pin', new_pin_path %></li>
          <li><%= link_to '프로필수정', edit_user_registration_path %>></li>
          <li><%= link_to '로그아웃', destroy_user_session_path, method: :delete %>></li>
        <% else %>
          <li><%= link_to '로그인', new_user_session_path %></li>
          <li><%= link_to '회원가입', new_user_registration_path %></li>
        <% end %>

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :pin_image %>
    <%= f.file_field :pin_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row pinterest-grid">
<% @pins.each do |pin| %>
  <div class="col-md-3 pin-item">
    <div class="panel panel-default pin">
      <div class="panel-body">
        <%= link_to image_tag(pin.pin_image.url(:medium)), pin %>
      </div>
      <div class="panel-footer">
        <p><strong><%= link_to pin.user.username, user_path(pin.user.username)%></strong></p>
        <p><%= pin.description %></p>
        <p><%= pluralize(pin.likes.count, 'Like') %></p>
        <%if pin.user == current_user %>
          <div>
            <%= link_to 'Edit', edit_pin_path(pin) %> |
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
        <% if user_signed_in? && pin.user !=current_user %>
          <div>
            <%= link_to 'Repost', repost_pin_path(pin), method: :POST, data: { confirm: 'want to pin?'} %>
            <%= link_to 'Like', like_pin_path(pin), method: :post, class: 'pull-right' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @pin.description %>
</p>
<div>
  <%= image_tag @pin.pin_image.url(:medium) %>
</div>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/users/show.html.erb
<div>
  <%= image_tag @user.avatar.url(:medium) %>
</div>
<h3><%= @user.username %></h3>
<p><%= @user.bio %></p>


<div class="row pinterest-grid">
<% @user.pins.each do |pin| %>
  <div class="col-md-3 pin-item">
    <div class="panel panel-default pin">
      <div class="panel-body">
        <%= link_to image_tag(pin.pin_image.url(:medium)), pin %>
      </div>
      <div class="panel-footer">
        <p><strong><%= link_to pin.user.username, user_path(pin.user.username)%></strong></p>
        <p><strong><%= pin.user.username %></strong></p>
        <p><%= pin.description %></p>
        <%if pin.user == current_user %>
          <div>
            <%= link_to 'Edit', edit_pin_path(pin) %> |
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>